### Apa itu NumPy?
NumPy (Numerical Python) adalah library Python untuk komputasi numerik yang memungkinkan manipulasi array multi-dimensional dengan berbagai fungsi matematika. NumPy menyediakan struktur data array yang efisien dan berbagai fungsi untuk operasi matematika, manipulasi data, dan analisis statistik. Library ini sangat efisien dan digunakan sebagai dasar untuk banyak library data analyst dan data science lainnya seperti Pandas, SciPy, dan Scikit-learn.

#### Pentingnya NumPy untuk Analisis Data
- Mempercepat operasi numerik melalui array yang efisien.
- Memiliki fungsi bawaan untuk analisis statistik, transformasi data, dan operasi matrix.
- Memungkinkan manipulasi dataset besar dengan cepat.

### Instalasi NumPy
Untuk menginstal NumPy, gunakan perintah berikut di terminal atau command prompt:
` pip install numpy `

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import random

# Buat data random dengan ukuran 10.000.000
size = 10

# Data Gaji Karyawan
gaji_karyawan = [random.randint(5000000, 15000000) for _ in range(size)]

# Data array Gaji
array_gaji = np.array(gaji_karyawan)
# print(gaji_karyawan)

In [3]:
%%timeit
# Mencari rata rata gaji dengan python
avg_gaji = sum(gaji_karyawan) / len(gaji_karyawan)

251 ns ± 28.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
%%timeit
# Mencari rata rata gaji dengan numpy python
avg_gaji1 = np.mean(array_gaji)

11.5 μs ± 420 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### Alasan:
NumPy dirancang untuk bekerja lebih cepat pada array besar karena dioptimalkan untuk operasi vektor (berbasis C). Namun, pada array kecil (misalnya list Python sederhana), overhead NumPy untuk memuat fungsi dan struktur data tambahan membuatnya lebih lambat.

Python bawaan lebih ringan untuk operasi sederhana seperti sum() dan len() pada list kecil.

### Membuat Array dari List

Array dapat dibuat dari list Python. Array NumPy lebih efisien dibandingkan list karena memiliki tipe data homogen.


- Membuat array 1D, 2D, dan 3D dari list

- Menggunakan fungsi ```np.array()```

- Mengatur tipe data pada array

In [5]:
# Membuat array 1D dengan function np.array()
list_1D = [1,2,3,4,5]
array_1D = np.array(list_1D, dtype=float)
print(f"array 1D : {array_1D}")

# Membuat array 2D 
list_2D = [[1,2,3],[4,5,6]]
array_2D = np.array(list_2D)
print(f"array 2D : \n {array_2D}")

# Membuat array 3D 
list_3D = [[[1,2],[3,4]],[[5,6],[7,8]]]
array_3D = np.array(list_3D)
print(f"array 3D : \n {array_3D}")


array 1D : [1. 2. 3. 4. 5.]
array 2D : 
 [[1 2 3]
 [4 5 6]]
array 3D : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
array_1D.dtype

dtype('float64')

### Membuat Array dengan np.arange()

Fungsi np.arange() digunakan untuk membuat array dengan elemen yang memiliki rentang tertentu dan langkah tertentu (mirip fungsi range() di Python).

Sintaks:
```
np.arange(start, stop, step, dtype=None)
```
- start: Nilai awal (default 0).

- stop: Nilai akhir (tidak termasuk).

- step: Langkah antar elemen (default 1).

- dtype: Tipe data elemen (opsional).

In [7]:
# Membuat array dari 0 hingga 9 step 1
array1 = np.arange(10)
print(f"Array 0 sampai 9 : {array1}")

# Membuat array dari 1 hingga 20 step 2
array2 = np.arange(1,21,2, dtype=float)
print(f"Array 0 sampai 9 : {array2}")

Array 0 sampai 9 : [0 1 2 3 4 5 6 7 8 9]
Array 0 sampai 9 : [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


### Membuat Array dengan np.zeros() dan np.ones()

Fungsi np.zeros() dan np.ones() digunakan untuk membuat array yang elemen-elemennya semua nol atau satu.

Sintaks:

- ``` np.zeros(shape, dtype=float) ```

- ``` np.ones(shape, dtype=float) ```

Parameter:

- shape: Dimensi array (tuple atau integer).

- dtype: Tipe data elemen (default float).

In [23]:
# Membuat array 1D nol
array_zeros = np.zeros(5, dtype=int)
print(f"Array 1D nol: {array_zeros}")

# Membuat array 3D satu
array_ones = np.ones((2,2,3), dtype=int)
print(f"Array 2D satu: {array_ones}")

Array 1D nol: [0 0 0 0 0]
Array 2D satu: [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


### Mengatur Dimensi Array

- Setelah membuat array, dimensi array dapat diubah menggunakan atribut .reshape() atau .shape.
- Untuk meratakan array dengan menggunakan flatten() 

In [33]:
array = np.arange(12)
print(f"array asli : {array}")

# Mengubah array ke 2D (3x4)
array_2d = array.reshape(3,4)
print(f"array 2D : {array_2d}")

# Mengubah array ke 3D (2x2x3)
array_3d = array.reshape(2,2,3)
print(f"array 3D : {array_3d}")

array.shape = (6,2)
print(array)

# Meratakan array 
array_flattened = array_2d.flatten()
print(f"array 2d jadi 1d : {array_flattened}")

array asli : [ 0  1  2  3  4  5  6  7  8  9 10 11]
array 2D : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array 3D : [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
array 2d jadi 1d : [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Indexing dan Slicing pada Array 
- Indexing digunakan untuk mengambil elemen tertentu dari array.
- Slicing digunakan untuk mengambil sebagian elemen array berdasarkan format [start:stop:step].

In [48]:
# Array 1D 
array_1d = np.array([10,20,30,40,50])
print(f"Element pertama : {array_1d[0]}")
print(f"Element terakhir : {array_1d[-1]}")
print(f"Slicing element 2 sampai 4 : {array_1d[1:4]}")

# Array 2D
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Element baris pertama, kolom 2: {array_2d[1,1]}")
print(f"Slice baris 1 dan 2, semua kolom: {array_2d[:2,:]}")
print(f"Slice semua baris, kolom 1 dan 2: {array_2d[:,1:3]}")

Element pertama : 10
Element terakhir : 50
Slicing element 2 sampai 4 : [20 30 40]
Element baris pertama, kolom 2: 5
Slice baris 1 dan 2, semua kolom: [[1 2 3]
 [4 5 6]]
Slice semua baris, kolom 1 dan 2: [[2 3]
 [5 6]
 [8 9]]


### Mengubah Nilai Elemen Array

Array NumPy mendukung pengubahan nilai elemen secara langsung dengan menggunakan indeks.

In [54]:
array = np.arange(6)
print(f"sebelum array dirubah : {array}")

array[0] = -1
array[-1] = 100
print(f"setelah dirubah : {array}")

array[1:4] = [10,20,30]
print(f"setelah dirubah ke 2 kali : {array}")

sebelum array dirubah : [0 1 2 3 4 5]
setelah dirubah : [ -1   1   2   3   4 100]
setelah dirubah ke 2 kali : [ -1  10  20  30   4 100]


### Operasi Matematika Dasar (+, -, *, /)

Operasi matematika pada NumPy array diterapkan secara elemen-per-elemen.

In [57]:
array = np.arange(5)
print(array)

array_add = array + 5
print(f"array setelah ditambahkan 5: {array_add}")

array_sub = array - 5
print(f"array setelah dikurangkan 5: {array_sub}")

array_mul = array * 5
print(f"array setelah dikali 5: {array_mul}")

array_div = array / 5
print(f"array setelah dibagi 5: {array_div}")

[0 1 2 3 4]
array setelah ditambahkan 5: [5 6 7 8 9]
array setelah dikurangkan 5: [-5 -4 -3 -2 -1]
array setelah dikali 5: [ 0  5 10 15 20]
array setelah dibagi 5: [0.  0.2 0.4 0.6 0.8]


### Atribut Array

NumPy menyediakan atribut seperti shape dan size untuk memeriksa dimensi dan jumlah elemen array.

In [62]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print(f"Shape array : {array.shape}")
print(f"Size array : {array.size}")

[[1 2 3]
 [4 5 6]]
Shape array : (2, 3)
Size array : 6


### Fungsi Statistik

Fungsi statistik seperti mean(), sum(), min(), dan max() dapat digunakan pada array.

In [69]:
array = np.array([1,2,3,4,5])

print(f"Rata rata: {array.mean()}")
print(f"Jumlah seluruh elemen: {array.sum()}")
print(f"Element minimum: {array.min()}")
print(f"Element maximum: {array.max()}")

Rata rata: 3.0
Jumlah seluruh elemen: 15
Element minimum: 1
Element maximum: 5


### Distribusi Probabilitas
Distribusi probabilitas digunakan untuk menggambarkan bagaimana data tersebar. NumPy menyediakan berbagai fungsi untuk membuat array sesuai distribusi tertentu.

#### Distribusi Normal

Distribusi normal memiliki penyebaran data yang simetris dan sering digunakan dalam statistik. 

Sintaks ```np.random.normal(loc, scale, size)```

- loc: Mean (rata-rata) distribusi (default 0).
- scale: Standar deviasi distribusi (default 1).
- size: Ukuran array.

In [77]:
array_normal = np.random.normal(loc=9,scale=1, size= 5)
print(array_normal)
print(array_normal.mean())

[ 8.28788133  8.89201494  9.45227022  9.31655074 10.115741  ]
9.212891644923193


#### Distribusi Uniform

Distribusi uniform memiliki probabilitas yang sama untuk semua nilai dalam rentang tertentu.

Sintaks : ```np.random.uniform(low, high, size)```
- low: Batas bawah (default 0).
- high: Batas atas (default 1).
- size: Ukuran array.

In [78]:
array_uniform = np.random.uniform(low=0, high=10, size=5)
print(array_uniform)

[0.61370326 9.08706026 1.05302047 2.92239337 9.53431143]
